create table public.admins (user_id uuid primary key references auth.users(id) on delete cascade);
alter table public.admins enable row level security;
create policy "Only own membership" on public.admins for select to authenticated using (user_id = (select auth.uid()));
grant select on public.admins to anon, authenticated;
create function public.is_admin() returns boolean language sql stable security invoker set search_path = '' as $$ select exists (select 1 from public.admins where user_id = (select auth.uid())); $$;
grant execute on function public.is_admin() to anon, authenticated;
create table public.site_settings (id integer primary key check (id=1), content jsonb not null check (jsonb_typeof(content)='object'), updated_at timestamptz not null default now());
alter table public.site_settings enable row level security;
create policy "Public invitation" on public.site_settings for select to anon, authenticated using (true);
create policy "Admin content" on public.site_settings for update to authenticated using ((select public.is_admin())) with check ((select public.is_admin()));
grant select on public.site_settings to anon, authenticated;
grant update on public.site_settings to authenticated;
create table public.rsvps (id uuid primary key, family_name text not null check (char_length(trim(family_name)) between 1 and 120), created_at timestamptz not null default now(), status text not null default 'confirmed' check (status='confirmed'));
create index rsvps_created_at_idx on public.rsvps(created_at desc);
alter table public.rsvps enable row level security;
create policy "Guests confirm" on public.rsvps for insert to anon, authenticated with check (status='confirmed' and created_at between now()-interval '1 minute' and now()+interval '1 minute');
create policy "Admin reads confirmations" on public.rsvps for select to authenticated using ((select public.is_admin()));
create policy "Admin removes confirmations" on public.rsvps for delete to authenticated using ((select public.is_admin()));
grant insert on public.rsvps to anon, authenticated;
grant select, delete on public.rsvps to authenticated;
insert into public.site_settings (id, content) values (1, '{}');
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values ('soundtracks','soundtracks',true,20971520,array['audio/mpeg','audio/mp4','audio/ogg','audio/wav','audio/x-wav']);
create policy "Public soundtrack" on storage.objects for select to anon,authenticated using (bucket_id='soundtracks');
create policy "Admin uploads soundtrack" on storage.objects for insert to authenticated with check (bucket_id='soundtracks' and (select public.is_admin()));
create policy "Admin replaces soundtrack" on storage.objects for update to authenticated using (bucket_id='soundtracks' and (select public.is_admin())) with check (bucket_id='soundtracks' and (select public.is_admin()));
create policy "Admin removes soundtrack" on storage.objects for delete to authenticated using (bucket_id='soundtracks' and (select public.is_admin()));
